// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// 部署
type Department struct {
	ID        string      `json:"id"`
	Name      string      `json:"name"`
	Employees []*Employee `json:"employees"`
}

// 従業員
type Employee struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Department *Department `json:"department"`
}
