package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"

	"github.com/im11u/gql-example/go/graph/generated"
	"github.com/im11u/gql-example/go/graph/model"
)

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context) ([]*model.Department, error) {
	// TODO
	return []*model.Department{
		{
			ID:        "employee01",
			Name:      "department01",
			Employees: []*model.Employee{},
		},
		{
			ID:        "employee02",
			Name:      "department02",
			Employees: []*model.Employee{},
		},
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
